<table class='table'>
    <tr>
        <td align='center'><img src='<?php echo $_layoutParams1['ruta_img'];?>LOGO2.png' width='70px' height='110px' alt='logo alcaldia'>
        </td>
        <td>
            <h3 align='center'>ALCALDIA DE OCOTAL</h3>
            <h4 align='center'>SISTEMA INTEGRAL DE PAGOS TRIBUTARIOS</h4>
        </td>
        <td align='center'><img src='<?php echo $_layoutParams1['ruta_img'];?>LOGO1.png' width='100px' height='70px'  alt='logo SIPT'>
        </td>

    </tr>

</table>
<br>
<?php
if(isset($this->reporte))echo $this->reporte;