<div id="contact-buttons-bar" class="slide-on-scroll" data-top="120px" style="left: 0px;">
    <button class="contact-button-link show-hide-contact-bar"><span class="fa fa-angle-left"></span></button>
    <a href="&lt;?php echo BASE_URL.'contribuyentes'" class="contact-button-link cb-ancor facebook" title="Follow on Facebook" target="_blank"><span class="fa fa-facebook">  Nombre1 Nombre1</span></a>
    <a href="https://www.linkedin.com/company/mycompany" class="contact-button-link cb-ancor linkedin" title="Visit on LinkedIn"><span class="fa fa-linkedin">Nombre2</span></a>
    <a href="https://plus.google.com/myidongoogle" class="contact-button-link cb-ancor gplus" title="Visit on Google Plus"><span class="fa fa-google-plus">Nombre3</span></a>
    <a href="http://github.com" class="contact-button-link cb-ancor git" title="My title for the button"><span class="fa fa-github">Nombre4</span></a>
    <a href="tel:+000" class="contact-button-link cb-ancor phone separated" title="Call us"><span class="fa fa-phone">Nombre5</span></a>
    <a href="mailto:test@web.com" class="contact-button-link cb-ancor email" title="Send us an email"><span class="fa fa-envelope">Nombre6</span></a>
</div>