<div class="container">
<div class="row">

<div class="col-lg-6 col-lg-offset-4">
<div class="panel panel-primary">
    <div class="panel-heading"><h4>Busqueda de Factura</h4></div>
    <div class="panel-body">
        <form class="" method="post" action="">
            <input name="buscarf" value="1" type="hidden" />
            <div class="input-group col-lg-6">
                <div class="input-group-addon">N° Factura:</div>
                <input required id="tfactura" class="form-control" type="text" name="nfactura" />
            </div>
            <br>

                <input id="bbuscar" type="submit" class="btn btn-primary" value="Buscar" />

        </form>

    </div>
</div>
</div>
</div>

<div class="row">
<div class="col-lg-6 col-lg-offset-4">
<div class="panel panel-default">
    <div class="panel-heading"><h4>Datos de Factura</h4></div>
    <div class="panel-body">
        <form class="" method="post" action="">
            <input name="pagarf" value="1" type="hidden" />


                <input  type="hidden" name="nfacturap" value="<?php if(isset($this->factura)) echo $this->factura; ?>" />

            <div class="input-group col-lg-6">
                <div class="input-group-addon">Estado</div>
                <input required id="testado" disabled class="form-control" type="text" name="estado" value="<?php if(isset($this->estado)) echo $this->estado; ?>" />
            </div>
            <br>
            <div class="input-group col-lg-6">
                <div class="input-group-addon">Total a Pagar</div>
                <input disabled class="form-control" type="text" name="totalpagar" value="<?php if(isset($this->total_pagar)) echo $this->total_pagar; ?>"/>
            </div>
            <br>
            <div class="input-group col-lg-6">
                <div class="input-group-addon">Fecha de Emisión</div>
                <input disabled class="form-control" type="text" name="fechae" value="<?php if(isset($this->fechagenerado)) echo $this->fechagenerado; ?>"/>
            </div>
            <br>
            <div class="input-group col-lg-4">
                <div class="input-group-addon">N° Boleta</div>
                <input required id="tboleta" class="form-control" type="text" name="boleta" />
            </div>

            <br>
            <div class="input-group col-lg-6">
                <div class="input-group-addon">Forma de Pago</div>
                <select name="forma_pago" class="form-control">
                    <option>Efectivo</option>
                    <option>Cheque</option>
                    <option>Transferencia</option>
                    <option>Tarjeta</option>
                </select>
            </div>
            <br>

            <div class="input-group col-lg-12">
                <div class="input-group-addon">Observacion</div>
                <input class="form-control" type="text" name="observacion" />
            </div>

            <br>

            <input type="submit" class="btn btn-danger" value="Pagar" />

        </form>

    </div>
</div>
</div>

</div>
</div>




<?php
if(isset($this->datos) && $this->datos==1){
    echo "<script>alert('El N° de Factura no existe');</script>";
    echo "<script>$('#tfactura').focus();</script>";

}

{
    if(isset($this->datos) && $this->datos==2)
    {
        echo "<script>alert('Esta Factura está Pagada');</script>";
        echo "<script>$('#tfactura').focus();</script>";
    }
    else
    echo "<script>$('#tboleta').focus();</script>";
}


if(isset($this->mensaje))
echo $this->mensaje;


?>

