
<nav>

    <div align="center">
        <h3>Registro de Usuarios</h3>
    </div>
</nav>

<br>


<div class="container">

    <form  action="" method="post" >

<input type="hidden" name="registrar" value="1"/>

        <div class="row">

            <div class="col-lg-6">
                <label class="sr-only" for="inlineFormInputGroup">Nombre</label>
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                    <div class="input-group-addon">Nombre y Apellidos</div>
                    <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="nombre" name="nombre" required />
                </div>
            </div>

            <div class="col-lg-3">
                <label class="sr-only" for="inlineFormInputGroup">Usuario</label>
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                    <div class="input-group-addon">Usuario</div>
                    <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Usuario" name="usuario" required />
                </div>
            </div>


            <div class="col-lg-3">
                <label class="sr-only" for="inlineFormInputGroup">contraseña</label>
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                    <div class="input-group-addon">Contraseña</div>
                    <input type="password" class="form-control" id="inlineFormInputGroup" placeholder="Contraseña" name="pass" required />
                </div>
            </div>


        </div>

        <br>


        <div class="row">

            <div class="col-lg-3">
                <label class="sr-only" for="inlineFormInputGroup">rol</label>
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                    <div class="input-group-addon">Cargo</div>
                    <select class="form-control" data-live-search="true" name="role" >
                        <?php if(Session::get('level')=='admin')
                        {
                         echo '<option>admin</option>
                        <option>especial</option>';
                        }

                        ?>
                        <option>usuario</option>
                        </select>
                </div>
            </div>

            <div class="col-lg-4">
                <label class="sr-only" for="inlineFormInputGroup">correo</label>
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                    <div class="input-group-addon">Dirección Electronica</div>
                    <input type="email" class="form-control" id="inlineFormInputGroup" placeholder="correo" name="email"  />
                </div>
            </div>

            <div class="col-lg-2">
                <label class="sr-only" for="form-control">Estado</label>
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                    <div class="input-group-addon">estado</div>
                    <select class="form-control" id="inlineFormInputGroup" placeholder="tipo"  name="estado">
                        <option>1</option>
                        <option>0</option>
                    </select>
                </div>
            </div>

            <div class="col-lg-3">
                <label class="sr-only" for="inlineFormInputGroup">Fecha Registro</label>
                <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                    <div class="input-group-addon">Fecha Registro</div>
                    <input type="date" class="form-control" id="inlineFormInputGroup" placeholder="Fecha" name="fecha" />
                </div>
            </div>

        </div>
        <br>
        <input type="submit" name="guardar" class="btn btn-primary col-lg-offset-5" value="Guardar" />

    </form>

<h5 class="text-danger"><?php if(isset($this->error)) echo $this->error;  ?></h5>
    <br>
    <br>

    <table class="table table-bordered" id='Jtabla'>
       <thead> <tr class="warning">
            <th >Nombre y Apellido</th>
            <th >Usuario</th>
            <th>Cargo</th>
            <th>Direccion electronica</th>
            <th>Fecha Regsitro</th>
            <th>Estado</th>
            <th>Acción</th>
        </tr>
       </thead>
        <tbody>
            <?= $this->listaUsuarios ?>
        </tbody>
    </table>

</div>








<?php if(isset($_layoutParams['js']) && count($_layoutParams['js']))
    for($i=0;$i<count($_layoutParams['js']);$i++)
        echo      "<script src='". $_layoutParams['js'][$i]."'></script>";
?>