
    <!-- **********************************************************************************************************************************************************
        MAIN SIDEBAR MENU
        *********************************************************************************************************************************************************** -->
    <!--sidebar start-->
    <aside>
    
      <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu" id="nav-accordion">
          <p class="centered"><a href="profile.html"><img src="<?php echo $_layoutParams['ruta_img'];?>user.png" class="img-circle" width="80"></a></p>
          <h5 class="centered">Nombre de usuario</h5>
          <li class="mt">
            <a class="active" href="index.html">
              <i class="fa fa-home"></i>
              <span>Inicio</span>
              </a>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-pencil"></i>
              <span>Marcar Asistencia </span>
              </a>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-question"></i>
              <span>Preguntas </span>
              </a>
          </li>
          <li class="sub-menu">
            <a href="javascript:;">
              <i class="fa fa-list-alt"></i>
              <span>Ver Calificaciones</span>
              </a>
            <ul class="sub">
              <li><a href="blank.html">Por Fecha</a></li>
              <li><a href="login.html">Materia</a></li>
              <li><a href="lock_screen.html">ver todo</a></li>
              
            </ul>
          </li>
          <li class="sub-menu">
            <a href="javascript:;">
              <i class="fa fa-tasks"></i>
              <span>Clases</span>
              </a>
            <ul class="sub">
              <li><a href="form_component.html">Verificar Id de clases</a></li>
              <li><a href="advanced_form_components.html">Historial de clases</a></li>
              
            </ul>
          </li>
          <li class="sub-menu">
            <a href="javascript:;">
              <i class="fa fa-th"></i>
              <span>Trabajos de Clases</span>
              </a>
            <ul class="sub">
              <li><a href="basic_table.html">Recibidos</a></li>
              <li><a href="responsive_table.html">Enviados</a></li>
            </ul>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-envelope"></i>
              <span>invitacion </span>
              <span class="label label-theme pull-right mail-info">2</span>
              </a>
          </li>
          
          <li>
            <a href="#">
              <i class="fa fa-map-marker"></i>
              <span>Configuracion </span>
              </a>
          </li>
        </ul>
        <div class="top-menu">
        <ul class="nav pull-right top-menu">
          <li><a class="logout" href="index/cerrar'">Cerrar seccion</a></li>
        </ul>
      </div>
        <!-- sidebar menu end-->
      </div>
    </aside>
    <!--sidebar end-->
    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
    <!--main content start-->
  
    <section id="main-content">
      <section class="wrapper site-min-height">
        <div class="row">
        </br>
          <div class="col-lg-9 ">
            <!--CUSTOM CHART START -->
            <div class="style-head">
              <h3>Ultimo Evento</h3>
            </div>
            
            <!--custom chart end-->
            <div  style="background-color:white " class="container-fluid lead fc-header-title h2" >
              
              

           <h2 class="text-center "> <strong> PROPOSICIONES PARA EL CONTROL DE FLUJO DE PROGRAMA </strong></h2>
    <p>&nbsp;</p>
    <ol>
        <li><strong><u> INTRODUCCION</u></strong></li>
    </ol>
    <p>En lo que sigue de este cap&iacute;tulo, denominaremos BLOQUE DE SENTENCIAS al conjunto de sentencias individuales inclu&iacute;das dentro un par de llaves. Por ejemplo :</p>
    <p>{</p>
    <p>sentencia 1 ;</p>
    <p>sentencia 2 ;</p>
    <p>.............</p>
    <p>sentencia n ;</p>
    <p>}</p>
    <p>Este conjunto se comportar&aacute; sintacticamente como una sentencia simple y la llave de cierre del bloque NO debe ir seguida de punto y coma .&nbsp;<br />Un ejemplo de bloque ya visto , es el cuerpo del programa principal de la funci&oacute;n main() .</p>
    <p>main()</p>
    <p>{</p>
    <p>bloque de sentencias</p>
    <p>}</p>
    <p>En las proposiciones de control de flujo de programa , trabajaremos alternativamente con sentencias simples y bloques de ellas .</p>
    <ol start="2">
        <li><strong><u> PROPOSICION IF - ELSE</u></strong></li>
    </ol>
    <p>Esta proposici&oacute;n sirve para ejecutar ciertas sentencias de programa , si una expresi&oacute;n resulta CIERTA &uacute; otro grupo de sentencias, si aquella resulta FALSA. Su interpretaci&oacute;n literal ser&iacute;a : SI es CIERTA tal cosa , haga tal otra , si no lo es salte&eacute;la .</p>
    <p>El caso m&aacute;s sencillo ser&iacute;a :</p>
    <p>if(expresi&oacute;n)</p>
    <p>&nbsp;sentencia ;</p>
    <p>&oacute;</p>
    <p>if(expresi&oacute;n)&nbsp; sentencia ;</p>
    <p>Cuando la sentencia que sigue al IF es &uacute;nica, las dos formas de escritura expresadas arriba son equivalentes . La sentencia s&oacute;lo se ejecutar&aacute; si el resultado de "expresi&oacute;n" es distinto de cero (CIERTO) , en caso contrario el programa saltear&aacute; dicha sentencia , realizando la siguiente en su flujo.&nbsp;<br />&nbsp;Veamos unos ejemplos de las distintas formas que puede adoptar la "expresi&oacute;n" dentro de un IF :&nbsp;<br />&nbsp;&nbsp;&nbsp;</p>

  
               
              <!-- /col-md-4 -->
            </div>
            <!-- /row -->
          </div>
          <!-- /col-lg-9 END SECTION MIDDLE -->
          <!-- **********************************************************************************************************************************************************
               Contenido SIDEBAR Derecho 
              *********************************************************************************************************************************************************** -->
          <div class="col-lg-3 ds">
            <!--panel derecho-->
            <div class="donut-main">
              <h4>Carrera  / año cursado</h4>
             <!-- WEATHER PANEL -->
              <div class="col-md-12"><!-- en el css style.css se carga el fondo  -->
                <div class="weather pn">
                  <i class="fa fa-book fa-4x"></i>
                  <h1>5º </h1>
                  <h3>Ing En Sistema</h3>
                </div>
              </div>
              
            </div>
           
            <!--  SECcion activades Recientes -->
            <div class="desc">
            <h3 class="centered mt">Cursos Recientes</h3>
                  </div>
            <!-- First Activity -->
            <div class="desc">
              <div class="thumb">
                <span class="badge bg-theme"><i class="fa fa-clock-o"></i></span>
              </div>
              <div class="details">
                <p>
                  <muted>Just Now</muted>
                  <br/>
                  <a href="#">Paul Rudd</a> purchased an item.<br/>
                </p>
              </div>
            </div>
            <!-- Second Activity -->
            <div class="desc">
              <div class="thumb">
                <span class="badge bg-theme"><i class="fa fa-clock-o"></i></span>
              </div>
              <div class="details">
                <p>
                  <muted>2 Minutes Ago</muted>
                  <br/>
                  <a href="#">James Brown</a> subscribed to your newsletter.<br/>
                </p>
              </div>
            </div>
            <!-- Third Activity -->
            <div class="desc">
              <div class="thumb">
                <span class="badge bg-theme"><i class="fa fa-clock-o"></i></span>
              </div>
              <div class="details">
                <p>
                  <muted>3 Hours Ago</muted>
                  <br/>
                  <a href="#">Diana Kennedy</a> purchased a year subscription.<br/>
                </p>
              </div>
            </div>
            <!-- Fourth Activity -->
            <div class="desc">
              <div class="thumb">
                <span class="badge bg-theme"><i class="fa fa-clock-o"></i></span>
              </div>
              <div class="details">
                <p>
                  <muted>7 Hours Ago</muted>
                  <br/>
                  <a href="#">Brando Page</a> purchased a year subscription.<br/>
                </p>
              </div>
            </div>
            
            <!-- CALENDAR-->
            <div id="calendar" class="mb">
              <div class="panel green-panel no-margin">
                <div class="panel-body">
                  <div id="date-popover" class="popover top" style="cursor: pointer; disadding: block; margin-left: 33%; margin-top: -50px; width: 175px;">
                    <div class="arrow"></div>
                    <h3 class="popover-title" style="disadding: none;"></h3>
                    <div id="date-popover-content" class="popover-content"></div>
                  </div>
                  <div id="my-calendar"></div>
                </div>
              </div>
            </div>
            <!-- / calendar -->
          </div>
          <!-- /col-lg-3 -->
        </div>
        <!-- /row -->
      </section>
    </section>
    <!--main content end-->
   