<form  name="formpropiedad" id="formpropiedad"  method="post" action="">
    <div class="modal-footer" Bienes Inmuebles id="propiedades_cliente">


        <input type="hidden" name="editarpropiedad" value="1" />
        <h4 class="modal-title" align ="center">Datos de los Bienes Inmuebles</h4>

        <br>

        <div class="row">
            <div class="col-xs-4">
                <div class="input-group-addon">Codigo Catastral</div>
                <input type="text" class="form-control" placeholder="Codigo Catastras" name="codigo" value="<?php if(isset($this->datosp['codigo'])) echo $this->datosp['codigo']; ?>">
            </div>
            <div class="col-xs-3">
                <div class="input-group-addon">Valor Catastral</div>
                <input type="text" class="form-control" placeholder="Valor catastral" name="valor" value="<?php if(isset($this->datosp['valor'])) echo $this->datosp['valor']; ?>">
            </div>
            <div class="col-xs-5">
                <div class="input-group-addon">Excepción</div>
                <select class="form-control" data-live-search="true" name="excepcion" >
                    <?php if(isset($this->datosp['excepcion'])) echo '<option>'.$this->datosp['excepcion'].'</option>'; ?>
                    <option data-tokens="ketchup mustard">Excepción de Impuesto</option>
                    <option data-tokens="mustard">No Aplica</option>
                    <option data-tokens="mustard">Jubila</option>
                    <option data-tokens="frosting">Discapacitado</option>
                    <option data-tokens="frosting">Sin Fines de Lucro</option>
                    <option data-tokens="frosting">Instituciones del Estado</option>
                </select>

            </div>
        </div>

        <br>
        <div class="row">
            <div class="col-xs-8"><div class="input-group-addon">Dirección de la Propiedad</div>
                <input type="text" class="form-control" placeholder="Direción de la Propiedad" name="direccion" value="<?php if(isset($this->datosp['direccion'])) echo $this->datosp['direccion']; ?>">
            </div>

            <div class="col-xs-4"><div class="input-group-addon">Barrio donde se Ubica la propiedad</div>
                <div class="">
                    <select class="form-control" data-live-search="true" name="barrio" >
                        <?php if(isset($this->datosp['barrio'])) echo '<option>'.$this->datosp['barrio'].'</option>'; ?>
                        <option data-tokens="ketchup mustard">Barrio donde se Ubica la Propiedad</option>
                        <option data-tokens="mustard">ANEXO YELBA MARIA ANTUNEZ</option>
                        <option data-tokens="mustard">YELBA MARIA ANTUNEZ</option>
                        <option data-tokens="mustard">DANILO PONCE</option>
                        <option data-tokens="mustard">JOSE SANTOS RODRIGUEZ</option>
                        <option data-tokens="mustard">LAURA SOFIA OLIVAS</option>
                        <option data-tokens="mustard">LEONARDO MATUTE</option>
                        <option data-tokens="mustard">ENRIQUE LACAYO FARFAN</option>
                        <option data-tokens="mustard">CARLOS MANUEL JARQUIN</option>
                        <option data-tokens="mustard">RAMON AUGUSTO LOPEZ</option>
                        <option data-tokens="mustard">SANDINO</option>
                        <option data-tokens="mustard">SAN ANTONIO DE TEJAS</option>
                        <option data-tokens="mustard">HERMANOS ZAMORA</option>
                        <option data-tokens="mustard">MONSEÑOR MADRIGAL</option>
                        <option data-tokens="mustard">NOEL WEELOCK</option>
                        <option data-tokens="mustard">ROBERTO GOMEZ</option>
                        <option data-tokens="mustard">26 DE SEPTIEMBRE</option>
                        <option data-tokens="mustard">CRISTO DEL ROSARIO</option>
                        <option data-tokens="mustard">19 DE JULIO</option>
                        <option data-tokens="mustard">REPARTO LAS SEGOVIAS</option>
                        <option data-tokens="mustard">NUEVO AMANECER</option>
                        <option data-tokens="mustard">EL TUNAL</option>
                        <option data-tokens="mustard">TOMAS BORGE</option>
                        <option data-tokens="mustard">JUAN CARLOS MENDOZA</option>
                        <option data-tokens="mustard">MODESTO AGURCIA</option>
                        <option data-tokens="mustard">EL QUEBRANTADERO</option>
                        <option data-tokens="mustard">PUEBLOS UNIDOS</option>
                        <option data-tokens="mustard">DINAMARCA</option>
                        <option data-tokens="mustard">TEODORO LOPEZ</option>
                        <option data-tokens="mustard">SAN NICOLAS DE TOLENTINO</option>
                        <option data-tokens="mustard">GRACIAS A DIOS</option>
                        <option data-tokens="mustard">MARIA AUXILIADORA</option>
                        <option data-tokens="mustard">LA FUENTE</option>
                        <option data-tokens="mustard">ANEXO LAURA SOFIA OLIVAS</option>
                        <option data-tokens="mustard">SANTA ANA</option>
                        <option data-tokens="mustard">NORA ASTORGA</option>
                        <option data-tokens="mustard">NICARAO</option>
                        <option data-tokens="mustard">JOSE SANTOS DUARTE</option>


                    </select>
                </div>
            </div>

        </div>

        <div class="row">
            <br>

            <div class="input-group col-lg-9 col-lg-offset-1">
                <div class="input-group-addon">Descripción de la Propiedad</div>
                <input class="form-control" type="text" placeholder="Ingrese la descripción de la propiedad" name="descripcion" value="<?php if(isset($this->datosp['descripcion'])) echo $this->datosp['descripcion']; ?>">
            </div>
        </div>



        <br>
        <!---a qui va el boto IBI--->
        <div class="modal-footer">
            <button type="buton" class="btn btn-default" data-dismiss="modal">Cerrar</button>

            <button type="buton" class="btn btn-primary">Guardar</button>

        </div>





    </div>

</form>
