<div class="">
    <div class="row">

        <?php
        if (isset($this->negocios_clientes) && count($this->negocios_clientes))
        {
            echo '<h4 class="alert-warning">Lista de Negocios</h4>';
            echo "<table class='table table-bordered table-hover'>
                <thead>Lista de Negocios</thead>
                   <tr><th>ID</th><th>Nombre Negocio</th><th>Número Matricula</th><th>Direccion</th><th>Tipo de Negocio</th><th>Clasificación</th><th>Acción</th><th>Acción</th></tr>";
            for($i=0;$i<count($this->negocios_clientes);$i++)
            {
                echo '<tr><td>'.$this->negocios_clientes[$i]['idn'].'</td>'.'<td>'.$this->negocios_clientes[$i]['nombrenegocio'].'</td>'.
                    "<td>".$this->negocios_clientes[$i]['matricula']."</td>.
             <td>".$this->negocios_clientes[$i]['direccion']."</td>.
              <td>".$this->negocios_clientes[$i]['tipo']."</td>.
              <td>".$this->negocios_clientes[$i]['clasificacion']."</td>.
                <td><a href='".BASE_URL."contribuyentes/editar_negocio/". $this->negocios_clientes[$i]['idn']. "'>Editar</a></td>
                <td><a href='".BASE_URL."contribuyentes/eliminar_negocio/". $this->negocios_clientes[$i]['idn']. "'>Eliminar</a></td></tr>";
            }
            echo '</table>';
        }
        else
            echo '<h4 class="alert-warning">No posee Negocios...........................................</h4>';
        ?>


    </div>
</div>