<?php if(isset($_layoutParams['js']) && count($_layoutParams['js']))
    for($i=0;$i<count($_layoutParams['js']);$i++)
        echo      "<script src='". $_layoutParams['js'][$i]."'></script>";
?>

<div align="center">
    <h2>IMPUESTOS DE LA OBLIGACION TRIBUTARIA</h2>
</div>

<div align="center">
    <h4>Código Catastral:   <?php echo $this->codigo_propiedad; ?></h4>
</div>
<br>
<div class="container">


    <div class="panel panel-info">
        <div class="panel-heading">Ingrese los Datos del Negocio</div>
        <div class="panel-body hidden-print">
            <form id="formpagospropiedad" method="post" action="">
                <input type="hidden" name="agregar" value="1" />
        <div class="row ">




            <div class="col-xs-12 col-sm-4 col-md-3 col-lg-3">

                <div class="input-group-addon">Seleccione el tributo</div>
                <select class="form-control" id="inlineFormInputGroup" placeholder="tipo" name="tributo">
                    <option>Matricula</option>
                    <option>Impuesto Sobre Ingresos</option>
                    <option>Impuesto de Bienes Inmuebles</option>
                    <option>Retenciones</option>
                    <option>Basura</option>
                    <option>Rotulo</option>
                </select>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-3 col-lg-7">
                <div class="input-group-addon">Descripcion</div>
                <textarea class="form-control" rows="2" placeholder="Descripcion" name="descripcion" required></textarea>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-3 col-lg-2">
                <div class="input-group-addon">Periodo, Mes -Año</div>
                <input type="text" class="form-control" required placeholder="Periordo del cobro" name="periodo" />
            </div>
        </div>

        <br>
        <div class="row ">
            <div class="col-xs-12 col-sm-4 col-md-2 col-lg-2">
                <div class="input-group-addon">Monto</div>
                <input type="text" class="form-control" required placeholder="Campo de numerico" name="monto" />
            </div>

            <div class="col-xs-12 col-sm-4 col-md-2 col-lg-2">
                <div class="input-group-addon">Multa</div>
                <input type="text" class="form-control" placeholder="Campo de numerico" name="multa" />
            </div>
            <div class="col-xs-12 col-sm-4 col-md-2 col-lg-2">
                <div class="input-group-addon">Deduccion</div>
                <input type="text" class="form-control" placeholder="Campo numerico" name="deduccion" />
            </div>
            <div class="col-xs-12 col-sm-4 col-md-2 col-lg-2">
                <div class="input-group-addon">Fecha de Emision</div>
                <input type="date" class="form-control" required placeholder="Fecha" name="fechae" />
            </div>
            <div class="col-xs-12 col-sm-4 col-md-2 col-lg-2">
                <div class="input-group-addon">Fecha de Caducidad</div>
                <input type="date" class="form-control" required placeholder="Fecha" name="fechac" />
            </div>
            <div class="col-xs-12 col-sm-4 col-md-2 col-lg-2">
                <div class="input-group-addon">Estado</div>
                <select class="form-control" id="inlineFormInputGroup" placeholder="tipo" name="estado" >
                    <option>Pendiente</option>
                    <option>Pagado</option>

                </select>
            </div>
        </div>

        <br>
                <input type="submit" class="btn btn-primary col-lg-offset-5"  value="Agregar"/>
            </form>
</div>
    </div>



    <br>


    <br>

<?php if(isset($this->lista_tributos_propiedad))
{
echo "
    <table class='table table-bordered ' id='Jtabla'><thead>
        <tr class='warning'>
            
            <th >Tributo</th>
            <th>Descripcion</th>
            <th>Periodo</th>
            <th>Monto</th>
            <th>Mora</th>
            <th>Deduccion</th>
            <th>F_Emision</th>
            <th>F_Caducidad</th>
            <th>Estado</th>
            <th>Acción</th>
        </tr></thead><tbody>";


for($i=0;$i<count($this->lista_tributos_propiedad);$i++)
    {
        echo "<tr>
                
                <td >".$this->lista_tributos_propiedad[$i]['tributo']."</td>
                <td >".$this->lista_tributos_propiedad[$i]['descripcion']."</td>
                <td >".$this->lista_tributos_propiedad[$i]['periodo']."</td>
                <td >".$this->lista_tributos_propiedad[$i]['monto']."</td>
                <td >".$this->lista_tributos_propiedad[$i]['multa']."</td>
                <td >".$this->lista_tributos_propiedad[$i]['deduccion']."</td>
                <td >".$this->lista_tributos_propiedad[$i]['fechaE']."</td>
                <td >".$this->lista_tributos_propiedad[$i]['fechaC']."</td>
                <td >".$this->lista_tributos_propiedad[$i]['estado']."</td>";
        if($this->lista_tributos_propiedad[$i]['estado']=='Pendiente')
          echo "<td ><a href=".BASE_URL."contribuyentes/eliminar_tributo_propiedad/".$this->lista_tributos_propiedad[$i]['idtp']." class='btn btn-danger hidden-print' title='Eliminar'><li class='fa fa-trash'></li></a></td></tr>";
        else
            echo "<td></td></tr>";
    }
}
     ?>


    </tbody></table>
</div>
