


<div class="col-lg-12">


    <div class="row ">
        <div class="col-lg-12">
            <?php
            if (isset($this->negocios_clientes) && count($this->negocios_clientes))
            {
                echo '<h4 class="alert-warning">Lista de Negocios</h4>';
                echo "<table class='table table-bordered table-hover'>
                
                   <tr><th>Nombre Negocio</th><th>Número Matricula</th><th>Direccion</th><th>Tipo de Negocio</th><th>Clasificación</th><th>Descripción</th><th>Acción</th></tr>";
                for($i=0;$i<count($this->negocios_clientes);$i++)
                {
                    echo '<tr><td>'.$this->negocios_clientes[$i]['nombrenegocio'].'</td>'.
                        "<td>".$this->negocios_clientes[$i]['matricula']."</td>
             <td>".$this->negocios_clientes[$i]['direccion']."</td>
              <td>".$this->negocios_clientes[$i]['tipo']."</td>
              <td>".$this->negocios_clientes[$i]['clasificacion']."</td>
              <td>".$this->negocios_clientes[$i]['descripcion']."</td>
                <td><a class='btn btn-primary hidden-print' title='Editar' href='".BASE_URL."contribuyentes/editar_negocio/". $this->negocios_clientes[$i]['idn'].  "'><i class='fa  fa-pencil' aria-hidden='true'></i></a>
                <a class='btn btn-info hidden-print' title='Cargar Cobro' href='".BASE_URL."contribuyentes/pago_negocio/". $this->negocios_clientes[$i]['idn']. "'><i class='fa  fa-usd' aria-hidden='true'></i></a>
                <a class='btn btn-danger hidden-print' title='Eliminar' href='".BASE_URL."contribuyentes/eliminar_negocio/". $this->negocios_clientes[$i]['idn']. "'><i class='fa  fa-trash' aria-hidden='true'></i></a></td></tr>";
                }
                echo '</table>';
            }
            else
                echo '<h4 class="alert-warning">No posee Negocios...........................................</h4>';
            ?>


        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <?php
            if (isset($this->propiedades_clientes) && count($this->propiedades_clientes))
            {
                echo '<h4 class="alert-warning">Lista de Propiedades</h4>';
                echo "<table class='table table-bordered table-hover'>
                     <tr><th>Código Catastral</th><th>Valor de la Propiedad</th><th>Excepción</th><th>Dirección</th><th>Barrio</th><th>Acción</th></tr>";
                for($i=0;$i<count($this->propiedades_clientes);$i++)
                {
                    echo '<tr><td>'.$this->propiedades_clientes[$i]['codigo'].'</td>'.
                        "<td>".$this->propiedades_clientes[$i]['valor']."</td>
             <td>".$this->propiedades_clientes[$i]['excepcion']."</td>
              <td>".$this->propiedades_clientes[$i]['direccion']."</td>
              <td>".$this->propiedades_clientes[$i]['barrio']."</td>
                <td><a class='btn btn-primary hidden-print' title='Editar' href='".BASE_URL."contribuyentes/editar_propiedad/". $this->propiedades_clientes[$i]['idp']. "'><i class='fa  fa-pencil' aria-hidden='true'></i></a>
                <a class='btn btn-info hidden-print' title='Cargar Cobro' href='".BASE_URL."contribuyentes/pago_propiedad/". $this->propiedades_clientes[$i]['idp']. "'><i class='fa  fa-usd' aria-hidden='true'></i></a>
                <a class='btn btn-danger hidden-print' title='Eliminar' href='".BASE_URL."contribuyentes/eliminar_propiedad/". $this->propiedades_clientes[$i]['idp']. "'><i class='fa  fa-trash' aria-hidden='true'></i></a></td></tr>";
                }
                echo '</table>';
            }
            else
                echo '<h4 class="alert-warning">No posee Propiedades...........................................</h4>';
            ?>


        </div>
    </div>
</div>



