
<nav class='clasein'>

    <div class='container'>

        <table class='table'>
            <tr>
                <td align='center'><img src='<?php echo $_layoutParams1['ruta_img'];?>LOGO2.png' width='70px' height='110px' alt='logo alcaldia'>
                </td>
                <td>
                    <h3 align='center'>ALCALDIA DE OCOTAL</h3>
                    <h4 align='center'>SISTEMA INTEGRAL DE PAGOS TRIBUTARIOS</h4>
                </td>
                <td align='center'><img src='<?php echo $_layoutParams1['ruta_img'];?>LOGO1.png' width='100px' height='70px'  alt='logo SIPT'>
                </td>

            </tr>

        </table>

        <div class='panel-body'>

            <div class='col-xs-12 col-sm-12 col-md-5 col-lg-12'><h4 align='center'>DATOS DEL CONTRIBUYENTE</h4></div>

            <br>
            <br>


            <table class='table'>
                <tr>

                    <th>N° de Cedula - RUC</th>
                    <th >Nombre del Contribuyente</th>
                    <th>Tipo de Persona</th>
                </tr>
                <tr style='border: inset 0pt'>
                    <td class='col-md-3 col-lg-3' style='border: inset 0pt'><?php if(isset($this->datos['RUC'])) echo $this->datos['RUC'];?>
                    </td>

                    <td class='col-md-6 col-lg-6' style='border: inset 0pt'><?php if(isset($this->datos['nombre'])) echo $this->datos['nombre'];?>
                    </td>
                    <td class='col-md-3 col-lg-3' style='border: inset 0pt'><?php if(isset($this->datos['tipo_persona'])) echo $this->datos['tipo_persona'];?>
                    </td>

                </tr>

                <tr>

                    <th>N° de Telefono</th>
                    <th>Direccion</th>
                    <th>Fecha de Registro</th>
                </tr>

                <tr>
                    <td class='col-md-3 col-lg-3' style='border: inset 0pt'><?php if(isset($this->datos['telefono'])) echo $this->datos['telefono'];else echo 'Sin Teléfono';?>
                    </td>

                    <td class='col-md-6 col-lg-6' style='border: inset 0pt'><?php if(isset($this->datos['direccion'])) echo $this->datos['direccion'];?>
                    </td>
                    <td class='col-md-3 col-lg-3' style='border: inset 0pt'><?php if(isset($this->datos['fecha_registro']) && count($this->datos['fecha_registro'])>0) echo $this->datos['fecha_registro']; else echo 'Sin Registro';?>
                    </td>
                </tr>

            </table>
            <br>

            <div class='col-xs-12 col-sm-12 col-md-5 col-lg-12 col-lg-offset-7'><h4>Obligaciones</h4></div>
            <div class="col-lg-6">
            <h5>Lista de Facturas</h5>
            <?= $this->FacturasPendientes ?>
            </div>
            <div class="col-lg-6">
            <?= $this->datos_negocios; ?>

                <table class="table table-condensed" style="width: 300px">
                    <tr class="active"><td>Total Bruto:</td><td>C$ <?= $this->total_pagar; ?></td></tr>
                    <tr class="success"><td>Total Deducciones:</td><td>C$ <?= $this->deducciones; ?></td></tr>
                    <tr class="warning"><td>Total Mora o Multa:</td><td>C$ <?= $this->mora; ?></td></tr>
                    <tr class="danger"><td><b>Total Neto:</b></td><td><b>C$ <?= $this->total_general; ?></b></td></tr>
                </table>


                <br>

                <a  return false;" <?= $this->estadoboton ?> href="<?= BASE_URL.'usuarios/generar_factura/'.$this->idco; ?>" class="btn btn-primary <?= $this->estadoboton ?>">Generar Factura</a>
            </div>


    </div>




</nav>

