
<nav class='clasein'>

    <div class='container'>

        <table class='table'>
            <tr>
                <td align='center'><img src='<?php echo $_layoutParams1['ruta_img'];?>LOGO2.png' width='70px' height='110px' alt='logo alcaldia'>
                </td>
                <td>
                    <h3 align='center'>ALCALDIA DE OCOTAL</h3>
                    <h4 align='center'>SISTEMA INTEGRAL DE PAGOS TRIBUTARIOS</h4>
                </td>
                <td align='center'><img src='<?php echo $_layoutParams1['ruta_img'];?>LOGO1.png' width='100px' height='70px'  alt='logo SIPT'>
                </td>

            </tr>

        </table>

        <div class='panel-body'>

            <div class='col-xs-12 col-sm-12 col-md-5 col-lg-12'><h4 align='center'>DATOS DEL CONTRIBUYENTE</h4></div>

            <br>
            <br>


            <table class='table'>
                <tr>

                    <th>N° de Cedula - RUC</th>
                    <th >Nombre del Contribuyente</th>
                    <th>Tipo de Persona</th>
                </tr>
                <tr style='border: inset 0pt'>
                    <td class='col-md-3 col-lg-3' style='border: inset 0pt'><?php if(isset($this->datos['RUC'])) echo $this->datos['RUC'];?>
                    </td>

                    <td class='col-md-6 col-lg-6' style='border: inset 0pt'><?php if(isset($this->datos['nombre'])) echo $this->datos['nombre'];?>
                    </td>
                    <td class='col-md-3 col-lg-3' style='border: inset 0pt'><?php if(isset($this->datos['tipo_persona'])) echo $this->datos['tipo_persona'];?>
                    </td>

                </tr>

                <tr>

                    <th>N° de Telefono</th>
                    <th>Direccion</th>
                    <th>Fecha de Registro</th>
                </tr>

                <tr>
                    <td class='col-md-3 col-lg-3' style='border: inset 0pt'><?php if(isset($this->datos['telefono'])) echo $this->datos['telefono'];else echo 'Sin Teléfono';?>
                    </td>

                    <td class='col-md-6 col-lg-6' style='border: inset 0pt'><?php if(isset($this->datos['direccion'])) echo $this->datos['direccion'];?>
                    </td>
                    <td class='col-md-3 col-lg-3' style='border: inset 0pt'><?php if(isset($this->datos['fecha_registro']) && count($this->datos['fecha_registro'])>0) echo $this->datos['fecha_registro']; else echo 'Sin Registro';?>
                    </td>
                </tr>

            </table>
            <br>


            <div class='col-xs-12 col-sm-12 col-md-5 col-lg-12'><h4 align='center'>Detalle de las obligaciones</h4></div>
            <br>
            <br>





            <?= $this->datos_negocios; ?>

            <table class="table col-lg-offset-8 table-condensed" style="width: 300px">
                <tr class="active"><td>Total Bruto:</td><td id="totalb">0</td></tr>
                <tr class="success"><td>Total Deducciones:</td><td id="totald">0</td></tr>
                <tr class="warning"><td>Total Mora o Multa:</td><td id="totalm">0</td></tr>
                <tr class="danger"><td><b>Total Neto:</b></td><td><b id="totaln">0</b></td></tr>
            </table>



        <div class="row ">
            <div class='col-xs-12 col-sm-12 col-md-5 col-lg-12'><h4 align='center'>Alcaldia Municipal Ocotal</h4></div></div>
        <div class="row ">
            <div class='col-xs-12 col-sm-12 col-md-5 col-lg-12'><h4 align='center'>Boleta de Pagos</h4></div></div>
        <table align='center' border="1">
            <tr style='border: inset 0pt'>

                <td><b>Nombre del Contribuyente:</b></td>
                <td><?php if(isset($this->datos['nombre'])) echo $this->datos['nombre'];?></td>
            </tr>
            <tr style='border: inset 0pt'>
                <td><b>Monto a pagar:</b></td>
                <td>c$ <?= $this->total_general; ?></td>
            </tr>

            <tr style='border: inset 0pt'>
                <td><b>Concepto:</b></td>
                <td>Pago de Impuesto Municipales</td>
            </tr>
            <tr style='border: inset 0pt'>
                <td><b>Fecha emision:</b></td>
                <td><?php echo date("m/d/Y"); ?></td>
            </tr>

            <tr style='border: inset 0pt'>
                <td><b>Cuenta Bampro N°:</b></td>
                <td>**********************</td>

            </tr>
        </table>


    </div>




</nav>
<script>

    $(document).ready(function() {

        $("input:checkbox").click(function() {
            var totalb=parseFloat( $('#totalb').text());
            var totald=parseFloat( $('#totald').text());
            var totalm=parseFloat( $('#totalm').text());
            var totaln=0;

            var idp=($(this).val());
           if ($(this).prop('checked')){
            totalb+=parseFloat($(".tb"+idp).text());
               totald+=parseFloat($(".td"+idp).text());
               totalm+=parseFloat($(".tm"+idp).text());
           }
            else{
            totalb-=parseFloat($(".tb"+idp).text());
               totald-=parseFloat($(".td"+idp).text());
               totalm-=parseFloat($(".tm"+idp).text());
           }
            totaln=totalb+totalm-totald;

            $('#totalb').text(totalb);
            $('#totald').text(totald);
            $('#totalm').text(totalm);
            $('#totaln').text(totaln);

        });

    });

</script>







<style>
    .funkyradio div {
        clear: both;
        overflow: hidden;
    }

    .funkyradio label {
        width: 100%;
        border-radius: 3px;
        border: 1px solid #D1D3D4;
        font-weight: normal;
    }

    .funkyradio input[type="radio"]:empty,
    .funkyradio input[type="checkbox"]:empty {
        display: none;
    }

    .funkyradio input[type="radio"]:empty ~ label,
    .funkyradio input[type="checkbox"]:empty ~ label {
        position: relative;
        line-height: 2.5em;
        text-indent: 3.25em;
      /*  margin-top: 2em; */
        cursor: pointer;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    .funkyradio input[type="radio"]:empty ~ label:before,
    .funkyradio input[type="checkbox"]:empty ~ label:before {
        position: absolute;
        display: block;
        top: 0;
        bottom: 0;
        left: 0;
        content: '';
        width: 2.5em;
        background: #D1D3D4;
        border-radius: 3px 0 0 3px;
    }

    .funkyradio input[type="radio"]:hover:not(:checked) ~ label,
    .funkyradio input[type="checkbox"]:hover:not(:checked) ~ label {
        color: #888;
    }

    .funkyradio input[type="radio"]:hover:not(:checked) ~ label:before,
    .funkyradio input[type="checkbox"]:hover:not(:checked) ~ label:before {
        content: '\2714';
        text-indent: .9em;
        color: #C2C2C2;
    }

    .funkyradio input[type="radio"]:checked ~ label,
    .funkyradio input[type="checkbox"]:checked ~ label {
        color: #777;
    }

    .funkyradio input[type="radio"]:checked ~ label:before,
    .funkyradio input[type="checkbox"]:checked ~ label:before {
        content: '\2714';
        text-indent: .9em;
        color: #333;
        background-color: #ccc;
    }

    .funkyradio input[type="radio"]:focus ~ label:before,
    .funkyradio input[type="checkbox"]:focus ~ label:before {
        box-shadow: 0 0 0 3px #999;
    }

    .funkyradio-default input[type="radio"]:checked ~ label:before,
    .funkyradio-default input[type="checkbox"]:checked ~ label:before {
        color: #333;
        background-color: #ccc;
    }

    .funkyradio-primary input[type="radio"]:checked ~ label:before,
    .funkyradio-primary input[type="checkbox"]:checked ~ label:before {
        color: #fff;
        background-color: #337ab7;
    }

    .funkyradio-success input[type="radio"]:checked ~ label:before,
    .funkyradio-success input[type="checkbox"]:checked ~ label:before {
        color: #fff;
        background-color: #5cb85c;
    }

    .funkyradio-danger input[type="radio"]:checked ~ label:before,
    .funkyradio-danger input[type="checkbox"]:checked ~ label:before {
        color: #fff;
        background-color: #d9534f;
    }

    .funkyradio-warning input[type="radio"]:checked ~ label:before,
    .funkyradio-warning input[type="checkbox"]:checked ~ label:before {
        color: #fff;
        background-color: #f0ad4e;
    }

    .funkyradio-info input[type="radio"]:checked ~ label:before,
    .funkyradio-info input[type="checkbox"]:checked ~ label:before {
        color: #fff;
        background-color: #5bc0de;
    }

</style>
