
<body>

    <div class="container" id="advanced-search-form">
        <h2>Registrate</h2>
        <form method="POST">
            <div class="form-group">
                <label for="first-name">Primer Nombre</label>
                <input type="text" class="form-control" placeholder=" Primer Nombre" id="first-name">
            </div>
            <div class="form-group">
                <label for="first-name">Segundo Nombre</label>
                <input type="text" class="form-control" placeholder=" Segundo Nombre" id="segnom">
            </div>
            <div class="form-group">
                <label for="last-name">Primer Apellido</label>
                <input type="text" class="form-control" placeholder="Primer Apellido" id="last-name">
            </div>
            <div class="form-group">
                <label for="last-name">Segundo Apellido</label>
                <input type="text" class="form-control" placeholder="Segundo Apellido" id="segap">
            </div>
            <div class="form-group">
                <label for="country">Ciudad</label>
                <input type="text" class="form-control" placeholder="Ciudad" id="country">
            </div>
            <div class="form-group">
                <label for="number">Numero de teléfono</label>
                <input type="text" class="form-control" placeholder="Numero de teléfono" id="number">
            </div>
            <div class="form-group">
                <label for="age">Edad</label>
                <input type="text" class="form-control" placeholder="Edad" id="age">
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" placeholder="Email" id="email">
            </div>
            <div class="form-group">
                <label for="category">Categoria</label>
                <input type="text" class="form-control" placeholder="Categoria" id="category">
            </div>
            <div class="form-group">
                <label for="education">Educacion</label>
                <input type="text" class="form-control" placeholder="Educacion" id="education">
            </div>
            <div class="form-group">
                <label>Genero</label>
                <div class="radio">
                    <label class="radio-inline">
                        <input type="radio" name="optradio">Masculino</label>
                    <label class="radio-inline">
                        <input type="radio" name="optradio">Femenino</label>
                </div>
            </div>
            <div class="clearfix"></div>
            <button type="submit" class="btn btn-info btn-lg btn-responsive" id="search"> <span class="glyphicon glyphicon-search"></span> Registrar</button>
        </form>
    </div>
</body>